# Generated by Django 5.0.3 on 2024-06-04 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicereview',
            name='comment',
            field=models.TextField(default='comment', verbose_name='Review Comment'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ReviewComment',
        ),
    ]
