# Generated by Django 5.0.3 on 2024-07-12 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_remove_service_points_purchase_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicediscount',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='services.service'),
        ),
    ]
