# Generated by Django 5.0.3 on 2024-07-13 12:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_servicediscount_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='points_earning_rate',
        ),
        migrations.AddField(
            model_name='service',
            name='points_gift',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(10000), django.core.validators.MinValueValidator(1)], verbose_name='Gifted points'),
            preserve_default=False,
        ),
    ]
