# Generated by Django 5.0.3 on 2024-07-23 23:42

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_remove_service_points_earning_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='refund_rate',
            field=models.DecimalField(decimal_places=1, max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.0')), django.core.validators.MaxValueValidator(Decimal('100.0'))]),
        ),
    ]
