# Generated by Django 5.0.3 on 2024-07-27 16:37

import profanity.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_alter_service_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicereview',
            name='comment',
            field=models.TextField(max_length=1024, validators=[profanity.validators.validate_is_profane], verbose_name='Review Comment'),
        ),
    ]
