# Generated by Django 5.0.3 on 2024-07-28 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_alter_servicereview_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='description_ar',
            field=models.TextField(blank=True, max_length=2048, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='service',
            name='description_en',
            field=models.TextField(blank=True, max_length=2048, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='service',
            name='description_es',
            field=models.TextField(blank=True, max_length=2048, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='service',
            name='description_fr',
            field=models.TextField(blank=True, max_length=2048, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='service',
            name='description_nl',
            field=models.TextField(blank=True, max_length=2048, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='service',
            name='name_ar',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='service',
            name='name_en',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='service',
            name='name_es',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='service',
            name='name_fr',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='service',
            name='name_nl',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Name'),
        ),
    ]
