# Generated by Django 5.0.3 on 2024-07-30 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_service_description_ar_service_description_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='allow_points',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='allow_review',
            field=models.BooleanField(default=True),
        ),
    ]
