# Generated by Django 5.0.7 on 2024-08-02 00:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_options'),
        ('services', '0008_alter_service_allow_points_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicediscount',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='events.event'),
        ),
        migrations.AlterField(
            model_name='servicediscount',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='services.service'),
        ),
        migrations.AddConstraint(
            model_name='servicediscount',
            constraint=models.UniqueConstraint(condition=models.Q(('service__isnull', True)), fields=('event',), name='unique_service_event_sd'),
        ),
    ]
