# Generated by Django 5.0.3 on 2024-08-17 09:58

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_alter_service_name_alter_service_name_ar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicediscount',
            name='percent',
            field=models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.0')), django.core.validators.MaxValueValidator(Decimal('79.0'))]),
        ),
    ]
