# Generated by Django 5.0.3 on 2024-06-28 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': (('manage_activities', 'Can manage Activities'), ('manage_properties', 'Can manage properties'), ('manage_car_rental', 'Can manage Car Rental')), 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
