# Generated by Django 5.0.3 on 2024-04-21 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False, help_text='checks if the user is an admin of the establishment site', verbose_name='admin status'),
        ),
    ]
