# Generated by Django 5.0.3 on 2024-04-21 21:34

import app_auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0004_alter_user_is_admin'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', app_auth.models.pwUserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False, help_text='checks if the user is an admin of the establishment site', verbose_name='admin status'),
        ),
    ]
