# Generated by Django 5.0.3 on 2024-07-27 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeminiResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=4096, verbose_name='Content made by Gemini')),
                ('prompt', models.TextField(verbose_name='Prompt for the AI')),
                ('temperature', models.FloatField(verbose_name='Sensitivity of the ai')),
                ('model', models.CharField(max_length=256, verbose_name='The model of the AI')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
