# Generated by Django 5.0.3 on 2024-05-17 12:01

import app_media.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Name')),
                ('bio', models.TextField(blank=True, max_length=2048, null=True, verbose_name="Guide's Bio")),
                ('avatar', app_media.models.AvatarField(max_length=1024, max_size=(128, 128), null=True, upload_to='uploads/guides/avatars', verbose_name='Avatar')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('likes', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
