# Generated by Django 5.0.3 on 2024-07-12 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listing',
            options={'ordering': ['-modified']},
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['-modified']},
        ),
        migrations.AlterModelOptions(
            name='tour',
            options={'ordering': ['-modified']},
        ),
        migrations.AlterModelOptions(
            name='toursite',
            options={'ordering': ['-modified']},
        ),
    ]
