# Generated by Django 5.0.3 on 2024-05-26 17:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='likers',
            field=models.ManyToManyField(related_name='liked_guides', through='activities.GuideLiker', to=settings.AUTH_USER_MODEL, verbose_name='Likers'),
        ),
    ]
