# Generated by Django 5.0.3 on 2024-05-21 19:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='guide',
            name='likers',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name=''),
        ),
    ]
