# Generated by Django 5.0.3 on 2024-05-17 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guide',
            old_name='likes',
            new_name='likers',
        ),
    ]
