# Generated by Django 5.0.3 on 2024-07-12 23:15

import djmoney.models.fields
import djmoney.models.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_alter_listing_options_alter_ticket_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='price',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default_currency='USD', max_digits=14, validators=[djmoney.models.validators.MinMoneyValidator(0.01)]),
        ),
    ]
