# Generated by Django 5.0.3 on 2024-06-07 19:11

import activities.validators
import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_site_description_alter_ticket_valid_until_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='valid_until',
            field=models.DateField(validators=[activities.validators.DateLessThanToday(datetime.datetime(2024, 6, 7, 19, 11, 48, 203922, tzinfo=datetime.timezone.utc))]),
        ),
        migrations.AlterField(
            model_name='tour',
            name='takeoff_date',
            field=models.DateTimeField(validators=[activities.validators.DateLessThanToday(datetime.datetime(2024, 6, 7, 19, 11, 48, 201936, tzinfo=datetime.timezone.utc))], verbose_name=''),
        ),
        migrations.AlterField(
            model_name='toursite',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_tours', to='activities.site', verbose_name='Site'),
        ),
        migrations.AlterField(
            model_name='toursite',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tour_sites', to='activities.tour', verbose_name='Tour'),
        ),
    ]
