# Generated by Django 5.0.3 on 2024-06-08 16:15

import activities.validators
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_alter_ticket_valid_until_alter_tour_takeoff_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='Link'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='valid_until',
            field=models.DateField(validators=[activities.validators.DateLessThanToday(datetime.datetime(2024, 6, 8, 16, 15, 50, 26355, tzinfo=datetime.timezone.utc))]),
        ),
        migrations.AlterField(
            model_name='tour',
            name='takeoff_date',
            field=models.DateTimeField(validators=[activities.validators.DateLessThanToday(datetime.datetime(2024, 6, 8, 16, 15, 50, 25355, tzinfo=datetime.timezone.utc))], verbose_name=''),
        ),
    ]
