# Generated by Django 5.0.3 on 2024-06-15 08:00

import activities.validators
import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0004_listing_website_alter_ticket_valid_until_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='stock',
            field=models.PositiveIntegerField(default=100, validators=[django.core.validators.MaxValueValidator(1000000), django.core.validators.MinValueValidator(1)], verbose_name='Stock'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='work_hours',
            field=models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MaxValueValidator(23.99)]),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='valid_until',
            field=models.DateField(validators=[activities.validators.DateLessThanToday(datetime.datetime(2024, 6, 15, 8, 0, 7, 99354, tzinfo=datetime.timezone.utc))]),
        ),
        migrations.AlterField(
            model_name='tour',
            name='takeoff_date',
            field=models.DateTimeField(validators=[activities.validators.DateLessThanToday(datetime.datetime(2024, 6, 15, 8, 0, 7, 97354, tzinfo=datetime.timezone.utc))], verbose_name=''),
        ),
    ]
