# Generated by Django 5.0.3 on 2024-07-14 23:06

import app_media.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0004_alter_listing_opens_at_alter_listing_site_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='photo',
            field=app_media.models.AvatarField(max_size=(1024, 1024), upload_to='uploads/sites', verbose_name='Photo'),
        ),
    ]
