# Generated by Django 5.0.3 on 2024-06-06 18:00

import activities.validators
import address.models
import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0005_ticket_description_alter_ticket_activity'),
        ('address', '0003_auto_20200830_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(days=10), verbose_name='Tour Duration'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tour',
            name='guide',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='activities.guide', verbose_name='Guide'),
        ),
        migrations.AddField(
            model_name='tour',
            name='takeoff_date',
            field=models.DateTimeField(default=datetime.date(2024, 6, 6), verbose_name=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ticket',
            name='valid_until',
            field=models.DateField(validators=[activities.validators.DateLessThanToday(datetime.datetime(2024, 6, 6, 17, 59, 35, 416620, tzinfo=datetime.timezone.utc))]),
        ),
        migrations.CreateModel(
            name='Attraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='')),
                ('order', models.PositiveIntegerField(verbose_name='Order')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('address', address.models.AddressField(on_delete=django.db.models.deletion.CASCADE, to='address.address')),
                ('tour', models.ForeignKey(max_length=2, on_delete=django.db.models.deletion.CASCADE, to='activities.tour', verbose_name='')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddConstraint(
            model_name='attraction',
            constraint=models.UniqueConstraint(fields=('tour', 'order'), name='unique_tour_order'),
        ),
    ]
