# Generated by Django 5.0.6 on 2024-07-24 23:48

import djmoney.models.fields
import djmoney.models.validators
from decimal import Decimal
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0005_alter_site_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='price',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default_currency='USD', max_digits=14, validators=[djmoney.models.validators.MinMoneyValidator(Decimal('0.01'))]),
        ),
    ]
