# Generated by Django 5.0.3 on 2024-07-03 19:31

import activities.validators
import datetime
import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0006_alter_activity_options_alter_ticket_points_rate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='price_in_points',
            new_name='points_discount_price',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='points_rate',
            new_name='points_discount',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='valid_until',
            field=models.DateField(validators=[activities.validators.DateLessThanToday(datetime.datetime(2024, 7, 3, 19, 30, 33, 845103, tzinfo=datetime.timezone.utc))]),
        ),
        migrations.AlterField(
            model_name='tour',
            name='takeoff_date',
            field=models.DateTimeField(validators=[activities.validators.DateLessThanToday(datetime.datetime(2024, 7, 3, 19, 30, 33, 843104, tzinfo=datetime.timezone.utc))], verbose_name=''),
        ),
    ]
