# Generated by Django 5.0.3 on 2024-07-26 13:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0006_activity_canceled_alter_ticket_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='canceled',
            field=models.BooleanField(default=False, verbose_name='Canceled'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='crucial_field_modified',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 7, 26, 13, 11, 48, 948673, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
