# Generated by Django 5.0.3 on 2024-07-26 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0006_alter_ticket_price'),
        ('activities', '0008_activity_crucial_field_modified'),
    ]

    operations = [
    ]
