# Generated by Django 5.0.3 on 2024-07-27 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0009_merge_20240727_0212'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='toursite',
            options={'ordering': ['order']},
        ),
    ]
