# Generated by Django 5.0.3 on 2024-07-28 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0010_alter_toursite_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='description_ar',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='description_es',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='description_fr',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='description_nl',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='name_ar',
            field=models.CharField(max_length=50, null=True, verbose_name='Name of the ticket'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='name_en',
            field=models.CharField(max_length=50, null=True, verbose_name='Name of the ticket'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='name_es',
            field=models.CharField(max_length=50, null=True, verbose_name='Name of the ticket'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='name_fr',
            field=models.CharField(max_length=50, null=True, verbose_name='Name of the ticket'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='name_nl',
            field=models.CharField(max_length=50, null=True, verbose_name='Name of the ticket'),
        ),
    ]
