# Generated by Django 5.0.3 on 2024-07-29 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0011_ticket_description_ar_ticket_description_en_and_more'),
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitytag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tags.tag'),
        ),
    ]
