# Generated by Django 5.0.3 on 2024-08-17 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0014_alter_activitytag_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listing',
            options={'ordering': ['modified']},
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['modified']},
        ),
        migrations.AlterModelOptions(
            name='tour',
            options={'ordering': ['modified']},
        ),
    ]
