# Generated by Django 5.0.3 on 2024-07-12 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketpurchase',
            name='canceled',
            field=models.BooleanField(default=False, verbose_name='Canceled'),
        ),
    ]
