# Generated by Django 5.0.3 on 2024-07-11 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketpurchase',
            name='canceled',
            field=models.BooleanField(default=False, verbose_name=''),
        ),
        migrations.AddField(
            model_name='ticketpurchase',
            name='scan_date',
            field=models.DateTimeField(null=True, verbose_name='Ticket scan date time'),
        ),
    ]
