# Generated by Django 5.0.3 on 2024-07-11 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_ticketpurchase_canceled_ticketpurchase_scan_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketpurchase',
            name='scan_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ticket scan date time'),
        ),
    ]
