# Generated by Django 5.0.3 on 2024-07-14 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0006_refund'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketpurchase',
            name='qr_code',
            field=models.ImageField(default='adsasdd', upload_to='reservations/tickets/qr_codes/', verbose_name='QR Code for uuid'),
            preserve_default=False,
        ),
    ]
