# Generated by Django 5.0.3 on 2024-07-26 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0007_ticket_canceled_ticket_crucial_field_modified'),
        ('reservations', '0008_alter_ticketpurchase_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketpurchase',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='activities.ticket', verbose_name='Ticket'),
        ),
    ]
