# Generated by Django 5.0.3 on 2024-07-28 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0009_alter_ticketpurchase_ticket'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticketpurchase',
            options={'ordering': ['-created'], 'permissions': (('scan_reservations', 'Can scan reservations'),)},
        ),
    ]
