# Generated by Django 5.0.3 on 2024-05-23 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tagscategory',
            name='role',
        ),
        migrations.DeleteModel(
            name='TagsCategoryPermission',
        ),
    ]
