# Generated by Django 5.0.6 on 2024-07-24 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'permissions': [('manage_event', 'Can manage event')]},
        ),
    ]
