# Generated by Django 5.0.6 on 2024-07-19 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
