# Generated by Django 5.0.3 on 2024-05-06 18:09

import app_media.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=app_media.models.AvatarField(max_length=1024, null=True, upload_to='uploads/profiles/avatars', verbose_name='Avatar'),
        ),
    ]
