# Generated by Django 5.0.6 on 2024-07-24 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suppropertyphoto',
            name='supproperty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='properties.supproperty'),
        ),
    ]
