# Generated by Django 5.0.7 on 2024-08-02 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_alter_suppropertyphoto_supproperty'),
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='propertytag',
            unique_together={('tag', 'property')},
        ),
        migrations.AlterUniqueTogether(
            name='suppropertytag',
            unique_together={('tag', 'supproperty')},
        ),
    ]
