# Generated by Django 5.0.3 on 2024-08-04 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_alter_propertytag_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertytag',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_tags', to='properties.property', verbose_name='Property'),
        ),
    ]
